---

- name: Yarn | GPG
  become: yes
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: Yarn | Ensure Debian sources list file exists
  become: yes
  file:
    path: /etc/apt/sources.list.d/yarn.list
    owner: root
    mode: 0644
    state: touch

- name: Yarn | Ensure Debian package is in sources list
  become: yes
  lineinfile:
    dest: /etc/apt/sources.list.d/yarn.list
    regexp: 'deb http://dl.yarnpkg.com/debian/ stable main'
    line: 'deb http://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: Yarn | Update APT cache
  become: yes
  apt:
    update_cache: yes

- name: Yarn | Install package
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - yarn
  become: yes
